name: 'Smart Comment Actions'
description: 'Create, update, append, delete or find pull request or issue comment'
inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: false
  repository:
    description: 'The GitHub repository'
    default: ${{ github.repository }}
    required: false
  type:
    description: create|update|append|delete|find
    required: true
  number:
    description: 'The number of the issue or pull request'
    required: false
  body:
    description: 'The comment body'
    required: false
  # Update/Append comment input
  # Delete comment input
  comment_id:
    description: 'Comment ID. Required to update or delete the comment'
    required: false
  # Find comment input
  search_term:
    description: 'Search term, which is included in the comment body.'
    required: false

outputs:
  comment_id:
    description: 'The id of the new comment'
  comment_body:
    description: 'The body of the new comment'

runs:
  using: 'node12'
  main: 'dist/index.js'
  # main: 'index.js'

branding:
  icon: 'message-circle'  
  color: 'blue'

