name: A workflow for my Hello World file
on:
  pull_request:
    types: [opened,synchronize]
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          type: "create"
          body: "Test comment on PR"
